"""Sync ARGUS weights and annotations to/from Hugging Face Hub.

Usage:
    # Upload everything (run from repo root):
    python scripts/sync_hf.py --upload

    # Upload only weights or only annotations:
    python scripts/sync_hf.py --upload --weights-only
    python scripts/sync_hf.py --upload --annotations-only

    # Download to a fresh machine (colleague setup):
    python scripts/sync_hf.py --download --weights-dir weights/ --annotations-dir /path/to/annotations/

Repos:
    lonewolfman22/argus-weights   (model repo)
    lonewolfman22/argus-dataset   (dataset repo)

Authentication:
    Run `huggingface-cli login` once, or set HF_TOKEN env var.
"""

from __future__ import annotations

import argparse
import logging
import os
from pathlib import Path

from huggingface_hub import HfApi, hf_hub_download, snapshot_download

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
log = logging.getLogger(__name__)

HF_USER = "lonewolfman22"
WEIGHTS_REPO = f"{HF_USER}/argus-weights"
DATASET_REPO = f"{HF_USER}/argus-dataset"

REPO_ROOT = Path(__file__).parent.parent
WEIGHTS_DIR = REPO_ROOT / "weights"
EXTERNAL_ANNOTATIONS = Path("/Volumes/External/TrainingData/annotations")

# Explicit allowlist — only current/active weights.
# Superseded runs (8–12, run_plain_dinov3) are excluded.
WEIGHTS_INCLUDE = [
    # Production heatmap detector
    "run15_vits/best.pt",
    "run15_vits/history.json",
    # Current experiment (ViT-B)
    "run17_vitb/best.pt",
    "run17_vitb/history.json",
    # DINOv3 pretrain backbones — required to load any of the above
    "dinov3_vits16_lvd1689m.pth",
    "dinov3_vitb16_pretrain_lvd1689m-73cec8be.pth",
    "dinov3_vitl16_lvd1689m.pth",
]
# Source annotations — original human labels, never regenerated by scripts.
ANNOTATIONS_SOURCE = [
    "all_train_run5_tiled_ts1800.json",   # Atwood train, pre-tiled 1800px
    "val_run17_fits.json",                 # Atwood val, full-frame, v2 labels
    "val_atwood.json",                     # Atwood val, full-frame, v1 labels
    "test_atwood.json",                    # Atwood test, full-frame
    "frigate_streaks.json",                # Frigate, all 350 frames
]

# Derived annotations — merged/processed snapshots used in specific training runs.
# Add a new entry here each time you produce a derived annotation set for a run.
# These are stored under annotations/derived/ in the dataset repo.
ANNOTATIONS_DERIVED = [
    "all_train_run17_merged.json",         # Run 17 training set (Atwood + Frigate + synth)
    "synth_run13_short_npy.json",          # Synthetic short streaks (used from Run 13 onward)
    "synth_run13_medium_npy.json",         # Synthetic medium streaks (used from Run 13 onward)
    "dev_subset.json",                     # 50-image reproducible dev subset
]


def upload_weights(api: HfApi) -> None:
    """Upload allowlisted weight files to the model repo."""
    log.info("Uploading weights/ → %s", WEIGHTS_REPO)
    for rel in WEIGHTS_INCLUDE:
        path = WEIGHTS_DIR / rel
        if not path.exists():
            log.warning("  MISSING (skipping): %s", rel)
            continue
        log.info("  uploading %s", rel)
        api.upload_file(
            path_or_fileobj=str(path),
            path_in_repo=rel,
            repo_id=WEIGHTS_REPO,
            repo_type="model",
        )
    log.info("Weights upload complete.")


def upload_annotations(api: HfApi) -> None:
    """Upload annotation JSONs from the external drive to the dataset repo."""
    if not EXTERNAL_ANNOTATIONS.exists():
        log.error(
            "External annotations directory not found: %s — is the drive mounted?",
            EXTERNAL_ANNOTATIONS,
        )
        return

    log.info("Uploading annotations/ → %s", DATASET_REPO)
    uploads = (
        [(name, "annotations/source") for name in ANNOTATIONS_SOURCE]
        + [(name, "annotations/derived") for name in ANNOTATIONS_DERIVED]
    )
    for name, repo_subdir in uploads:
        path = EXTERNAL_ANNOTATIONS / name
        if not path.exists():
            log.warning("  MISSING (skipping): %s", name)
            continue
        repo_path = f"{repo_subdir}/{name}"
        log.info("  uploading %s → %s", name, repo_path)
        api.upload_file(
            path_or_fileobj=str(path),
            path_in_repo=repo_path,
            repo_id=DATASET_REPO,
            repo_type="dataset",
        )
    log.info("Annotations upload complete.")


def download_weights(dest: Path, api: HfApi) -> None:
    """Download all weights from the model repo."""
    dest.mkdir(parents=True, exist_ok=True)
    log.info("Downloading %s → %s", WEIGHTS_REPO, dest)
    snapshot_download(
        repo_id=WEIGHTS_REPO,
        repo_type="model",
        local_dir=str(dest),
        ignore_patterns=["*.DS_Store"],
    )
    log.info("Weights download complete → %s", dest)


def download_annotations(dest: Path, api: HfApi) -> None:
    """Download annotation JSONs from the dataset repo.

    Downloads into dest/source/ and dest/derived/ matching the repo layout.
    Symlinks dest/source/<file> → dest/<file> so existing scripts that reference
    the flat annotations/ path still work without changes.
    """
    dest.mkdir(parents=True, exist_ok=True)
    log.info("Downloading annotations from %s → %s", DATASET_REPO, dest)
    snapshot_download(
        repo_id=DATASET_REPO,
        repo_type="dataset",
        local_dir=str(dest),
        ignore_patterns=["*.DS_Store"],
    )
    # Create flat symlinks for backwards compatibility with scripts that use
    # annotations/<name>.json directly (e.g. build_run17_annotations.py).
    for subdir in ("source", "derived"):
        subpath = dest / subdir
        if not subpath.exists():
            continue
        for f in subpath.glob("*.json"):
            link = dest / f.name
            if not link.exists():
                link.symlink_to(f)
    log.info("Annotations download complete → %s", dest)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--upload", action="store_true", help="Push local files to HF")
    mode.add_argument("--download", action="store_true", help="Pull files from HF")

    parser.add_argument("--weights-only", action="store_true", help="Only sync weights")
    parser.add_argument("--annotations-only", action="store_true", help="Only sync annotations")

    # Download destinations (override defaults for colleague machines)
    parser.add_argument(
        "--weights-dir",
        type=Path,
        default=WEIGHTS_DIR,
        help="Local weights directory (default: weights/)",
    )
    parser.add_argument(
        "--annotations-dir",
        type=Path,
        default=EXTERNAL_ANNOTATIONS,
        help="Local annotations directory (default: /Volumes/External/TrainingData/annotations/)",
    )

    args = parser.parse_args()

    token = os.environ.get("HF_TOKEN")
    api = HfApi(token=token)

    do_weights = not args.annotations_only
    do_annotations = not args.weights_only

    if args.upload:
        if do_weights:
            upload_weights(api)
        if do_annotations:
            upload_annotations(api)
    else:
        if do_weights:
            download_weights(args.weights_dir, api)
        if do_annotations:
            download_annotations(args.annotations_dir, api)


if __name__ == "__main__":
    main()
